trainer:
  name: Trainer
  namespace: scripts.snake_ai
  args:
    width: 16
    height: 16
    actor_output_dim: 4
    critic_output_dim: 1
    state_dim: 6
    hidden_dim: 512
    checkpoints_dir: 'checkpoints/snake'

train:
  max_iter: 100000
  batch_size: 256
  target_step: 4096
  lr: 0.0001
  repeat_times: 1
  gamma: 0.99
  reward_scale: 1
  vision_mode: False
  hungry_mode: True
  hungry_max: 150

test:
  update_mode: 5
  window_size:
    - 800
    - 800
  checkpoint_name: best_actor_abstract.pth
  vision_mode: False
  hungry_mode: True
  hungry_max: 150